version: 2.1

# Define the workflows we want to run for this project
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/SimpleApplication
    steps:
      - checkout
      - run: 
          name: Update npm
          command: npm install -g npm@8.1.4
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command:ssh -o StrictHostKeyChecking=no $EC2_x20460516@$EC2_PUBLIC_DNS \"rm -rf SimpleApplication/ && git clone https://github.com/Fawas32/SimpleApplication.git && source SimpleApplication/deploy.sh"
