version: 2.1

# Define the workflows to execute
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@8.1.4
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  deploy:
  docker:
    - image: circleci/node:10.16.3
  steps:
    - run:
        name: deploy-application
        command: |
          ssh -o StrictHostKeyChecking=no $EC2_x20460516@$EC2_PUBLIC_DNS "rm -rf SimpleApplication/; git clone https://github.com/Fawas32/SimpleApplication; cd SimpleApplication && ls -la && source deploy.sh"
